# Generated by Django 4.2.7 on 2026-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_covers/', verbose_name='Обложка темы'),
        ),
    ]
