# Generated by Django 4.2.7 on 2026-01-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Forum', max_length=100)),
                ('logo_text', models.CharField(blank=True, max_length=100)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип (картинка)')),
                ('description', models.TextField(blank=True)),
                ('game_title', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='🎮', max_length=10)),
                ('primary_color', models.CharField(default='#4E1260', max_length=7)),
                ('secondary_color', models.CharField(default='#0f1923', max_length=7)),
                ('meta_description', models.TextField(blank=True)),
                ('items_per_page', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Forum Configuration',
                'verbose_name_plural': 'Forum Configuration',
            },
        ),
    ]
